services:
  spark:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/home/jovyan/code
    ports:
      - "8888:8888"
      - "4040:4040"
    command: start.sh jupyter lab --ServerApp.token='' --ServerApp.disable_check_xsrf=true --ServerApp.allow_origin='*' --ServerApp.ip='0.0.0.0'
